steps:
  - block: ":raised_hand: Set Maintenance Window"
    prompt: |
      Until we sort through a suspected Supervisor bug, releases have
      the potential to cause instability in Builder. Please declare a
      maintenance window in Statuspage before proceeding any further.

  - label: ":right-facing_fist: :boom: :left-facing_fist: Promote Release in Builder"
    command: .buildkite/scripts/promote_release_channel.sh
    agents:
      queue: habitat-release

  - block: ":habicat: Wait until Builder is stabilized"
    prompt: |
      Until we sort through a suspected Supervisor bug, it is possible
      that Builder can get destabilized once the Supervisor has been
      promoted to the stable channel. This should be less of an issue
      as our operations and software mature, but until then, it is
      nice to explicitly factor that into our release process.

  - label: "Publish DockerHub Release"
    command: .buildkite/scripts/dockerhub_publish.sh
    agents:
      # All artifacts can be published from a Linux machine
      queue: habitat-release

  - label: "Publish Bintray Releases"
    command: .buildkite/scripts/bintray_publish.sh
    agents:
      # All artifacts can be published from a Linux machine
      queue: habitat-release

  - label: ":mac: Promote Homebrew Release"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Build Bootstrap Bundle and push to :s3:"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Add core/backline to Acceptance Environment"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Rebuild and promote the worker"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: ":github: Publish Github Release"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: "Update Documentation"
    command: /bin/true
    skip: Not implemented yet
    agents:
      queue: habitat-release

  - label: ":habicat: :boom: Destroy release channel"
    command: .buildkite/scripts/destroy_release_channel.sh
    agents:
      queue: habitat-release
